In [1]:
import numpy as np
import matplotlib.pylab as plt
from PIL import Image
import os


def photosAppend():
    path = "photos"
    photospath = []
    if(os.path.exists(path)):
        for root,d_names,f_names in os.walk(path):
            for f in f_names:
                photospath = np.append(photospath,os.path.join(root, f))    
    return photospath



def photosSave():
    photospath=photosAppend()
    
    photos = np.zeros([photospath.size,200,200,3])

    for i in range(photospath.size):
        ima=Image.open(photospath[i]).resize((200,200))
        ima.save(photospath[i])
        im = plt.imread(photospath[i])
        print(type(im))
        print(im.shape)
        photos[i] = im

    return photos   


def main():
    return photosSave()
    

if __name__ == "__main__": 
    print(main())

<class 'numpy.ndarray'>
(200, 200, 3)
<class 'numpy.ndarray'>
(200, 200, 3)
<class 'numpy.ndarray'>
(200, 200, 3)
[[[[106. 108. 120.]
   [107. 109. 121.]
   [108. 110. 122.]
   ...
   [106. 115. 124.]
   [105. 114. 123.]
   [104. 113. 122.]]

  [[106. 108. 120.]
   [107. 109. 121.]
   [108. 110. 122.]
   ...
   [106. 115. 124.]
   [105. 114. 123.]
   [104. 113. 122.]]

  [[107. 109. 121.]
   [108. 110. 122.]
   [109. 111. 123.]
   ...
   [107. 116. 125.]
   [105. 114. 123.]
   [105. 114. 123.]]

  ...

  [[ 70.  69.  65.]
   [ 70.  69.  65.]
   [ 71.  70.  66.]
   ...
   [ 73.  72.  68.]
   [ 73.  72.  68.]
   [ 73.  72.  68.]]

  [[ 64.  63.  59.]
   [ 65.  64.  60.]
   [ 67.  66.  62.]
   ...
   [ 75.  74.  70.]
   [ 75.  74.  70.]
   [ 75.  74.  70.]]

  [[ 66.  65.  61.]
   [ 67.  66.  62.]
   [ 69.  68.  64.]
   ...
   [ 65.  64.  60.]
   [ 64.  63.  59.]
   [ 63.  62.  58.]]]


 [[[185. 217. 255.]
   [185. 217. 255.]
   [185. 217. 255.]
   ...
   [209. 229. 255.]
   [209. 229. 25